### PR TITLE
Update token if expired

### PR DESCRIPTION
**Pull request by hackervera**
This library currently gets a token and expiration date from Rackspace but never actually uses it for anything. So, two days after you make your first request, it will stop working because you have an expired token. This PR makes it so the token will automatically get updated with a new one if it is past the token expiration time.

### CODE REVIEW

**Comment by hackervera** [comment]
Possibly. The date functions in erlang/elixir are notoriously bad. There is a movement to get Timex merged into elixir core: http://stackoverflow.com/questions/28594646/getting-the-current-date-and-or-time-in-elixir#comment45496845_28594969

Timex is like the Joda Time of the Elixir world

**Comment by moxley** [comment]
Erlang's built-in `calendar` library sure doesn't give much help on the matter.

**Comment by moxley** [comment]
How's this looking? Can we merge this?

**Comment by ewitchin** [comment]
Looks good guys, sorry for the delay!

**Pull request merged**
